# Quick interactive type declarations. Must be last in the $PROFILE execution
using namespace System
using namespace System.Collections
using namespace System.Collections.Generic
using namespace System.ComponentModel
using namespace System.Data
using namespace System.Data.OleDb
using namespace System.Data.Odbc
using namespace System.Diagnostics
using namespace System.Diagnostics.CodeAnalysis
using namespace System.IO
using namespace System.IO.Compression
using namespace System.Linq.Expressions
using namespace System.Management.Automation
using namespace System.Management.Automation.Language
using namespace System.Management.Automation.Runspaces
using namespace System.Net
using namespace System.Net.NetworkInformation
using namespace System.Net.Sockets
using namespace System.Reflection
using namespace System.Reflection.Emit
using namespace System.Reflection.PortableExecutable
using namespace System.Resources
using namespace System.Runtime.InteropServices
using namespace System.Security.AccessControl
using namespace System.Text
using namespace System.Text.RegularExpressions
using namespace System.Threading.Tasks
using namespace Microsoft.PowerShell.Commands
using namespace Microsoft.PowerShell
using namespace Microsoft.Win32
using namespace System.Xml
