[pwshAlias]
[pwshAlias.all]
acnt = "Add-Content"
add = "string\\Add-String"
addrm = "Add-DbaDbRoleMember"
adsrm = "Add-DbaServerRoleMember"
at = "MyProfile\\Select-ObjectIndex"
badb = "Backup-DbaDatabase"
ccdi = "Connect-DbaInstance"
ccvi = "VMWare.VimAutomation.Core\\Connect-VIServer"
cfcsv = "ConvertFrom-Csv"
cfhtml = "PSParseHTML\\ConvertFrom-HTML"
cfjson = "ConvertFrom-Json"
cfsecs = "ConvertFrom-SecureString"
ctcsv = "ConvertTo-Csv"
ctdxes = "ConvertTo-DbaXESession"
cthtml = "ConvertTo-Html"
ctjson = "ConvertTo-Json"
ctsecs = "ConvertTo-SecureString"
epclix = "Export-CliXml"
epddr = "Export-DbaDbRole"
epdl = "Export-DbaLogin"
epdscr = "Export-DbaScript"
epdsr = "Export-DbaServerRole"
epdu = "Export-DbaUser"
epdxes = "Export-DbaXESession"
epxl = "Export-Excel"
fddaj = "Find-DbaAgentJob"
fddb = "Find-DbaDatabase"
fddcmd = "Find-DbaCommand"
fddsp = "Find-DbaStoredProcedure"
fddvw = "Find-DbaView"
format = "string\\Format-String"
frg = "Invoke-PsFzfRipgrep"
fscoop = "Invoke-FuzzyScoop"
gado = "Get-ADObject"
gctr = "Get-Counter"
gdagd = "Get-DbaAgDatabase"
gdaj = "Get-DbaAgentJob"
gdajh = "Get-DbaAgentJobHistory"
gdash = "Get-DbaAgentSchedule"
gdb = "Get-DbaDatabase"
gdbf = "Get-DbaDbFile"
gdbu = "Get-DbaDbUser"
gdconf = "Get-DbaSpConfigure"
gddbh = "Get-DbaDbBackupHistory"
gddr = "Get-DbaDbRole"
gddrm = "Get-DbaDbRoleMember"
gdds = "Get-DbaDiskSpace"
gdept = "Get-DbaEndPoint"
gderr = "Get-DbaErrorLog"
gdl = "Get-DbaLogin"
gdps = "Get-DbaProcess"
gdreg = "Get-DbaRegServer"
gdsp = "Get-DbaDbStoredProcedure"
gdsr = "Get-DbaServerRole"
gdsrm = "Get-DbaServerRoleMember"
gdsv = "Get-DbaService"
gdtb = "Get-DbaDbTable"
gduf = "Get-DbaDbUdf"
gdvw = "Get-DbaDbView"
gdxeo = "Get-DbaXEObject"
gdxes = "Get-DbaXESession"
gdxest = "Get-DbaXEStore"
gdxesta = "Get-DbaXESessionTarget"
gdxestaf = "Get-DbaXESessionTargetFile"
gdxestp = "Get-DbaXESessionTemplate"
gipa = "Get-NetIPAddress"
gires = "Get-InstalledPSResource"
"git.exe" = "git"
groute = "Get-NetRoute"
gscht = "ScheduledTasks\\Get-ScheduledTask"
gschti = "ScheduledTasks\\Get-ScheduledTaskInfo"
gtcpc = "Get-NetTCPConnection"
gvm = "VMWare.VimAutomation.Core\\Get-VM"
gwe = "Get-WinEvent"
idq = "Invoke-DbaQuery"
idwho = "Invoke-DbaWhoIsActive"
ipclix = "Import-CliXml"
ipxl = "Import-Excel"
isudo = "Invoke-Gsudo"
ndaj = "New-DbaAgentJob"
ndb = "New-DbaDatabase"
ndbu = "New-DbaDbUser"
nddr = "New-DbaDbRole"
ndl = "New-DbaLogin"
ndsr = "New-DbaServerRole"
ndxes = "New-DbaXESession"
no = "New-Object"
onl = "Out-Null"
rdaj = "Remove-DbaAgentJob"
rdb = "Remove-DbaDatabase"
rdbu = "Remove-DbaDbUser"
rddr = "Remove-DbaDbRole"
rddrm = "Remove-DbaDbRoleMember"
rdl = "Remove-DbaLogin"
rdsr = "Remove-DbaServerRole"
rdsrm = "Remove-DbaServerRoleMember"
rdxes = "Remove-DbaXESession"
replace = "string\\Set-String"
rvdns = "Resolve-DnsName"
s = "Select-Object"
sadaj = "Start-DbaAgentJob"
sadsv = "Start-DbaService"
sadxes = "Start-DbaXESession"
scnt = "Set-Content"
sdaj = "Set-DbaAgentJob"
sdconf = "Set-DbaSpConfigure"
sdl = "Set-DbaLogin"
spdaj = "Stop-DbaAgentJob"
spdps = "Stop-DbaProcess"
spdsv = "Stop-DbaService"
spdxes = "Stop-DbaXESession"
split = "string\\Split-String"
tcn = "Test-Connection"
tdcn = "Test-DbaConnection"
trim = "string\\Get-SubString"
usres = "Uninstall-PSResource"
wcdxes = "Watch-DbaXESession"
wrap = "string\\Add-String"
[pwshAlias.windows]
"choco.exe" = "choco"
[pwshAlias.core]
cfclix = "ConvertFrom-CliXml"
ctclix = "ConvertTo-CliXml"
gsc = "Get-Secret"
gsci = "Get-SecretInfo"
ukv = "Unlock-SecretVault"
[pwshAlias.desktop]
join = "string\\Join-String"

